version: '3.2'

services:
  docker-php-fpm:
    build: provisioning/php-fpm
    ports:
     - "9000:9000"
    networks:
      - backend
    volumes:
        - ./:/app/
    
  docker-mysql:
    image: mysql:8.0
    ports: 
      - "3306:3306"
    networks:
      - backend
    volumes:
      - ./dbdata/:/var/lib/mysql
      - ./provisioning/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW?err}
      MYSQL_DATABASE: ${DB_NAME?err}

  docker-web:
    image: nginx:1.15
    ports:
      - "80:80"
    networks:
      - backend
    volumes:
      - ./:/app/
      - ./provisioning/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - docker-php-fpm
      - docker-mysql

  docker-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
     - 8080:80
    networks:
      - backend
    volumes:
      - /sessions
    depends_on:
        - docker-mysql
    environment:
      - PMA_HOST=docker-mysql
      - PMA_PORT=3306

networks:
  backend:
